### ISSUE TITLE
TypeError: Cannot use 'in' operator to search

### ISSUE THREAD

**Issue by sr793** [mauriciom75/node-red-contrib-wait-paths#2]
Hi,

in any configuration I always got this error: TypeError: Cannot use 'in' operator to search for 'path_1' in undefined

I use Node-RED 0.17.5 with Node.js v8.9.3

Thanks in advance,
N.

**Comment by mauriciom75** [comment]
Thank kou for you comment.

Please try the example configuration provided in the readme File. this works fine with the versions that you mention. I try it today.

You can go to option menu "import" a then "from clipboard" a then paste the json of the example in the imput box.

Any input paths must be set the messge variable msg.paths["input path name"]. The "input path name" must be exists in the configured property "paths" of wait-paths node. The property "paths" contains a json with a list of "path names"

if the "paths" variable is undefined when wait-path node executes, you will get this error. Y will work to improve the error message.

Regards.

**Comment by mauriciom75** [comment]
I have added new validations to improve error messages.
Best regards!
