### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by werling** [mauriciom75/node-red-contrib-wait-paths#3]
Somehow it was not possible to install this node.
I haven't found it in the palette manager and after I installed it with "npm install node-red-contrib-wait-paths", the node didnt pop ap in node-red.

Do you have an idea why?

Thanks for your help.

**Comment by mauriciom75** [comment]
This worked well. What version of node-red are you using?

**Comment by mauriciom75** [comment]
Hello, thanks to the help of Mr knolleary who detected an erroneous value in the field "readme" in package.json.
The problem is already solved.

Thanks for notifying the problem.
 
Wrong value:
"readme": "**ERROR: No README data found!**",
