### ISSUE TITLE
Combined message topic : suggestion

### ISSUE THREAD

**Issue by evryschu** [mauriciom75/node-red-contrib-wait-paths#6]
Hi Mariciom75,

Great node, and will be very useful in my project. Just one suggestion I'd like to make :

Would it be possible to select the joined message topic and payload based on a specific path? Currently it seems that the first message arriving forms the joined message topic. I have three paths coming in at irregular frequencies - however I want the topic of [path_1] to be passed on ; not the first or last message arriving. 
My 10 cents : add the option of a "path reference" to the "base message" option (currently first or last message). 

It would be great if you could look into this and maybe you have an easy solution :-)    

Many Thanks in advance!

Regards,
Evry

Below the flow I am using ; I want to check power generated (solar cells) to ensure heating pumps run once a week only when power is sufficient. The joined message goes into a function node to calculate and pass on a start command to the respective pump. I hope it is clear! 

[{"id":"91f750ad.e6e02","type":"tab","label":"Verbruiksmeter","disabled":false,"info":""},{"id":"73a69e37.5cada","type":"mqtt out","z":"91f750ad.e6e02","name":"Outdoor lights","topic":"home/verlichting/buiten/all","qos":"","retain":"","broker":"b088b754.972088","x":560,"y":100,"wires":[]},{"id":"431bc7b3.f69fc8","type":"debug","z":"91f750ad.e6e02","name":"output","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":550,"y":180,"wires":[]},{"id":"433a98b6.c38958","type":"ui_button","z":"91f750ad.e6e02","name":"","group":"f51c38ba.1bd2c8","order":0,"width":0,"height":0,"passthru":true,"label":"Buitenverlichting","tooltip":"","color":"","bgcolor":"","icon":"","payload":"A","payloadType":"str","topic":"home/verlichting/buiten/all","x":160,"y":260,"wires":[["73a69e37.5cada"]]},{"id":"37423dd1.3c7f22","type":"inject","z":"91f750ad.e6e02","name":"Alle lampen uit","topic":"home/verlichting/buiten/all","payload":"U","payloadType":"str","repeat":"","crontab":"30 02 * * *","once":false,"onceDelay":"0.1","x":180,"y":100,"wires":[["73a69e37.5cada","431bc7b3.f69fc8"]]},{"id":"c6ac96d0.5b84e8","type":"smooth","z":"91f750ad.e6e02","name":"10 minutes average","property":"payload","action":"mean","count":"60","round":"0","mult":"multi","reduce":false,"x":510,"y":460,"wires":[["fb2de918.94a548"]]},{"id":"cec40fee.5ed94","type":"inject","z":"91f750ad.e6e02","name":"Evaluate Net Power","topic":"","payload":"NetPower","payloadType":"global","repeat":"10","crontab":"","once":false,"onceDelay":"0.1","x":140,"y":580,"wires":[["613744d3.5e7c8c","bbf3e0a.3a1992","6b1be1cf.7d71e"]]},{"id":"613744d3.5e7c8c","type":"debug","z":"91f750ad.e6e02","name":"Net Power","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":430,"y":620,"wires":[]},{"id":"87a61451.226af8","type":"smooth","z":"91f750ad.e6e02","name":"2 minutes average","property":"payload","action":"mean","count":"12","round":"0","mult":"multi","reduce":false,"x":510,"y":520,"wires":[["fb2de918.94a548"]]},{"id":"88cd0add.2f8558","type":"mqtt out","z":"91f750ad.e6e02","name":"CV pompen","topic":"","qos":"","retain":"","broker":"b088b754.972088","x":1570,"y":580,"wires":[]},{"id":"87d0df11.efbb3","type":"trigger","z":"91f750ad.e6e02","op1":"1","op2":"","op1type":"num","op2type":"num","duration":"6","extend":false,"units":"hr","reset":"","bytopic":"topic","name":"Weekly interval heater pump","x":1120,"y":580,"wires":[["5d09dce6.b90f34"]]},{"id":"bbf3e0a.3a1992","type":"change","z":"91f750ad.e6e02","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"10minAverage","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":460,"wires":[["c6ac96d0.5b84e8"]]},{"id":"6b1be1cf.7d71e","type":"change","z":"91f750ad.e6e02","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"2minAverage","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":520,"wires":[["87a61451.226af8"]]},{"id":"1c71dafa.8df905","type":"inject","z":"91f750ad.e6e02","name":"PompHuis","topic":"Pomp_01","payload":"","payloadType":"date","repeat":"300","crontab":"","once":true,"onceDelay":"2","x":350,"y":340,"wires":[["3919ce73.5cca72"]]},{"id":"fb2de918.94a548","type":"join","z":"91f750ad.e6e02","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"3","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"num","reduceFixup":"","x":690,"y":580,"wires":[["6a214127.3db15","25f3dcb.049c324"]]},{"id":"25f3dcb.049c324","type":"debug","z":"91f750ad.e6e02","name":"Average","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1000,"y":640,"wires":[]},{"id":"6a214127.3db15","type":"function","z":"91f750ad.e6e02","name":"PwrCalc","func":"Avg1Power = 300;    // 2 minute average Power\nAvg2Power = 200;    // 10 minute average Power\n\nvar Avg1 = msg.payload[\"2minAverage\"];\nvar Avg2 = msg.payload[\"10minAverage\"];\nvar topic = msg.topic;\n//var PumpStat = msg.payload[topic];\nvar status = 0;\n\n// Pass message \"1\" when averages above threshold\n\n//if ((Avg1 >= Avg1Power) &&  (Avg2 >= Avg2Power) && PumpStat == 1) {\nif ((Avg1 >= Avg1Power) &&  (Avg2 >= Avg2Power)) {\n    status = 1;   //&& (Avg2 >= Avg2Power)\n//    return[{topic : PumpStat, payload : status}];\n    return[{topic : topic, payload : status}];\n}\nelse return;\n\n","outputs":1,"noerr":0,"x":860,"y":580,"wires":[["87d0df11.efbb3"]]},{"id":"44238659.777998","type":"inject","z":"91f750ad.e6e02","name":"PompSchuur","topic":"Pomp_02","payload":"","payloadType":"date","repeat":"300","crontab":"","once":true,"onceDelay":"2","x":360,"y":400,"wires":[["3919ce73.5cca72"]]},{"id":"5d09dce6.b90f34","type":"trigger","z":"91f750ad.e6e02","op1":"A","op2":"U1","op1type":"str","op2type":"str","duration":"5","extend":false,"units":"min","reset":"","bytopic":"topic","name":"Cycle pump","x":1370,"y":540,"wires":[["88cd0add.2f8558","5d5ae089.84128"]]},{"id":"5d5ae089.84128","type":"debug","z":"91f750ad.e6e02","name":"Outcome","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1480,"y":680,"wires":[]},{"id":"3919ce73.5cca72","type":"delay","z":"91f750ad.e6e02","name":"","pauseType":"queue","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"30","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":600,"y":360,"wires":[["f12e228e.f43da"]]},{"id":"f12e228e.f43da","type":"function","z":"91f750ad.e6e02","name":"SeasonCalc","func":"// Cycle CV pumps in the following months\nstartMonth = 4; // April start\nstopMonth = 10; // October end\n\nvar TimeStamp = msg.payload;\nvar topic = msg.topic;\nvar date;\n\ndate = new Date(TimeStamp);\nvar month = date.getMonth()+1;\n\nif (month >= startMonth && month <= stopMonth) return[{topic : topic, payload : month}];\nelse return;\n","outputs":1,"noerr":0,"x":810,"y":360,"wires":[["fb2de918.94a548"]]},{"id":"799b6c57.d74894","type":"smooth","z":"91f750ad.e6e02","name":"10 minutes average","property":"payload","action":"mean","count":"60","round":"0","mult":"multi","reduce":false,"x":590,"y":920,"wires":[["60bcd1b.d9e203"]]},{"id":"75504006.a4ccb","type":"inject","z":"91f750ad.e6e02","name":"Evaluate Net Power","topic":"","payload":"NetPower","payloadType":"global","repeat":"10","crontab":"","once":false,"onceDelay":"0.1","x":220,"y":1040,"wires":[["162cd436.b9cf5c","596e7d32.2cda94","cf0e3a83.f4cd38"]]},{"id":"162cd436.b9cf5c","type":"debug","z":"91f750ad.e6e02","name":"Net Power","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":510,"y":1080,"wires":[]},{"id":"d781ed6a.230fd","type":"smooth","z":"91f750ad.e6e02","name":"2 minutes average","property":"payload","action":"mean","count":"12","round":"0","mult":"multi","reduce":false,"x":590,"y":980,"wires":[["60bcd1b.d9e203"]]},{"id":"596e7d32.2cda94","type":"change","z":"91f750ad.e6e02","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"10minAverage","tot":"str"},{"t":"set","p":"paths","pt":"msg","to":"path_3","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":920,"wires":[["799b6c57.d74894"]]},{"id":"cf0e3a83.f4cd38","type":"change","z":"91f750ad.e6e02","name":"","rules":[{"t":"set","p":"topic","pt":"msg","to":"2minAverage","tot":"str"},{"t":"set","p":"paths","pt":"msg","to":"path_2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":980,"wires":[["d781ed6a.230fd"]]},{"id":"cceceeb5.4cd71","type":"inject","z":"91f750ad.e6e02","name":"PompHuis","topic":"Pomp_01","payload":"","payloadType":"date","repeat":"15","crontab":"","once":true,"onceDelay":"2","x":430,"y":800,"wires":[["7c63dbba.e5fd74"]]},{"id":"44391f64.24629","type":"function","z":"91f750ad.e6e02","name":"PwrCalc","func":"Avg1Power = 300;    // 2 minute average Power\nAvg2Power = 200;    // 10 minute average Power\n\nvar Avg1 = msg.payload[\"2minAverage\"];\nvar Avg2 = msg.payload[\"10minAverage\"];\nvar topic = msg.topic;\n//var PumpStat = msg.payload[topic];\nvar status = 0;\n\n// Pass message \"1\" when averages above threshold\n\n//if ((Avg1 >= Avg1Power) &&  (Avg2 >= Avg2Power) && PumpStat == 1) {\nif ((Avg1 >= Avg1Power) &&  (Avg2 >= Avg2Power)) {\n    status = 1;   //&& (Avg2 >= Avg2Power)\n//    return[{topic : PumpStat, payload : status}];\n    return[{topic : topic, payload : status}];\n}\nelse return;\n\n","outputs":1,"noerr":0,"x":1220,"y":1160,"wires":[[]]},{"id":"e56ba4e1.78af28","type":"inject","z":"91f750ad.e6e02","name":"PompSchuur","topic":"Pomp_02","payload":"","payloadType":"date","repeat":"15","crontab":"","once":true,"onceDelay":"2","x":440,"y":860,"wires":[["7c63dbba.e5fd74"]]},{"id":"7c63dbba.e5fd74","type":"delay","z":"91f750ad.e6e02","name":"","pauseType":"queue","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"10","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"x":680,"y":800,"wires":[["26cd4580.64202a"]]},{"id":"26cd4580.64202a","type":"function","z":"91f750ad.e6e02","name":"SeasonCalc","func":"// Cycle CV pumps in the following months\nstartMonth = 4; // April start\nstopMonth = 10; // October end\n\nvar TimeStamp = msg.payload;\nvar topic = msg.topic;\nvar date;\n\ndate = new Date(TimeStamp);\nvar month = date.getMonth()+1;\n\nif (month >= startMonth && month <= stopMonth) return msg ;\n//return[{object : topic, topic : topic, payload : month}];\nelse return;\n","outputs":1,"noerr":0,"x":890,"y":820,"wires":[["ca2ca0c9.7e2d4"]]},{"id":"ca2ca0c9.7e2d4","type":"change","z":"91f750ad.e6e02","name":"","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_1","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":1100,"y":820,"wires":[["60bcd1b.d9e203","bd15732b.c2988"]]},{"id":"60bcd1b.d9e203","type":"join-wait","z":"91f750ad.e6e02","name":"","paths":"[\"path_1\", \"path_2\", \"path_3\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"paths","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"1","timeoutUnits":"60000","exactOrder":"false","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":860,"y":980,"wires":[["48925071.f0278"],[]]},{"id":"48925071.f0278","type":"debug","z":"91f750ad.e6e02","name":"Average","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1080,"y":960,"wires":[]},{"id":"bd15732b.c2988","type":"debug","z":"91f750ad.e6e02","name":"test","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1270,"y":900,"wires":[]},{"id":"b088b754.972088","type":"mqtt-broker","z":"","name":"Homey Eexterveen","broker":"192.168.1.31","port":"1883","clientid":"","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"f51c38ba.1bd2c8","type":"ui_group","z":"","name":"Default","tab":"fa4ffcbe.a59b7","order":1,"disp":true,"width":"6","collapse":false},{"id":"fa4ffcbe.a59b7","type":"ui_tab","z":"","name":"Verbruik","icon":"dashboard","disabled":false,"hidden":false}]

**Comment by mauriciom75** [comment]
Hello evryschu,

Sorry for the delay, Thanks for using the node!

Currently this node is supporting your requeriment. The first configured "path" in the "paths array" indicates the path of de "base message". If a message from the first configured path does not arrive, the node utilizes the first arrived message as the "base message".

I ussually use the first path to send a direct message without complex processing to ensure the arriving of base message (if it is possible).

Later I will see your flow as soon as I can.

Regards,
Mauricio

**Comment by mauriciom75** [comment]
Hello, I was able to see your flow. I see you are using the "join-wait" node which is a derived node from this project. It is likely that it will also work in the same way. If it doesn't work for you, please let me know. Thanks!
